//#line 2 "/opt/ros/kinetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"
// *********************************************************
// 
// File autogenerated for the cooperative_driving_logic package 
// by the dynamic_reconfigure package.
// Please do not edit.
// 
// ********************************************************/

#ifndef __cooperative_driving_logic__REFLEKTESERVERCONFIG_H__
#define __cooperative_driving_logic__REFLEKTESERVERCONFIG_H__

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/Group.h>
#include <dynamic_reconfigure/config_init_mutex.h>
#include <boost/any.hpp>

namespace cooperative_driving_logic
{
  class ReflekteServerConfigStatics;
  
  class ReflekteServerConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l, 
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }
      
      virtual void clamp(ReflekteServerConfig &config, const ReflekteServerConfig &max, const ReflekteServerConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const ReflekteServerConfig &config1, const ReflekteServerConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, ReflekteServerConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const ReflekteServerConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, ReflekteServerConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const ReflekteServerConfig &config) const = 0;
      virtual void getValue(const ReflekteServerConfig &config, boost::any &val) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;
    
    template <class T>
    class ParamDescription : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string a_name, std::string a_type, uint32_t a_level, 
          std::string a_description, std::string a_edit_method, T ReflekteServerConfig::* a_f) :
        AbstractParamDescription(a_name, a_type, a_level, a_description, a_edit_method),
        field(a_f)
      {}

      T (ReflekteServerConfig::* field);

      virtual void clamp(ReflekteServerConfig &config, const ReflekteServerConfig &max, const ReflekteServerConfig &min) const
      {
        if (config.*field > max.*field)
          config.*field = max.*field;
        
        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const ReflekteServerConfig &config1, const ReflekteServerConfig &config2) const
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, ReflekteServerConfig &config) const
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const ReflekteServerConfig &config) const
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, ReflekteServerConfig &config) const
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const ReflekteServerConfig &config) const
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }

      virtual void getValue(const ReflekteServerConfig &config, boost::any &val) const
      {
        val = config.*field;
      }
    };

    class AbstractGroupDescription : public dynamic_reconfigure::Group
    {
      public:
      AbstractGroupDescription(std::string n, std::string t, int p, int i, bool s)
      {
        name = n;
        type = t;
        parent = p;
        state = s;
        id = i;
      }

      std::vector<AbstractParamDescriptionConstPtr> abstract_parameters;
      bool state;

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &config) const =0;
      virtual void updateParams(boost::any &cfg, ReflekteServerConfig &top) const= 0;
      virtual void setInitialState(boost::any &cfg) const = 0;


      void convertParams()
      {
        for(std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = abstract_parameters.begin(); i != abstract_parameters.end(); ++i)
        {
          parameters.push_back(dynamic_reconfigure::ParamDescription(**i));
        }
      }
    };

    typedef boost::shared_ptr<AbstractGroupDescription> AbstractGroupDescriptionPtr;
    typedef boost::shared_ptr<const AbstractGroupDescription> AbstractGroupDescriptionConstPtr;

    template<class T, class PT>
    class GroupDescription : public AbstractGroupDescription
    {
    public:
      GroupDescription(std::string a_name, std::string a_type, int a_parent, int a_id, bool a_s, T PT::* a_f) : AbstractGroupDescription(a_name, a_type, a_parent, a_id, a_s), field(a_f)
      {
      }

      GroupDescription(const GroupDescription<T, PT>& g): AbstractGroupDescription(g.name, g.type, g.parent, g.id, g.state), field(g.field), groups(g.groups)
      {
        parameters = g.parameters;
        abstract_parameters = g.abstract_parameters;
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        if(!dynamic_reconfigure::ConfigTools::getGroupState(msg, name, (*config).*field))
          return false;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          if(!(*i)->fromMessage(msg, n))
            return false;
        }

        return true;
      }

      virtual void setInitialState(boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        T* group = &((*config).*field);
        group->state = state;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = boost::any(&((*config).*field));
          (*i)->setInitialState(n);
        }

      }

      virtual void updateParams(boost::any &cfg, ReflekteServerConfig &top) const
      {
        PT* config = boost::any_cast<PT*>(cfg);

        T* f = &((*config).*field);
        f->setParams(top, abstract_parameters);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          (*i)->updateParams(n, top);
        }
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &cfg) const
      {
        const PT config = boost::any_cast<PT>(cfg);
        dynamic_reconfigure::ConfigTools::appendGroup<T>(msg, name, id, parent, config.*field);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          (*i)->toMessage(msg, config.*field);
        }
      }

      T (PT::* field);
      std::vector<ReflekteServerConfig::AbstractGroupDescriptionConstPtr> groups;
    };
    
class DEFAULT
{
  public:
    DEFAULT()
    {
      state = true;
      name = "Default";
    }

    void setParams(ReflekteServerConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("max_velocity"==(*_i)->name){max_velocity = boost::any_cast<double>(val);}
        if("max_turn_rate"==(*_i)->name){max_turn_rate = boost::any_cast<double>(val);}
        if("line_row_location"==(*_i)->name){line_row_location = boost::any_cast<int>(val);}
        if("LF_K_p"==(*_i)->name){LF_K_p = boost::any_cast<double>(val);}
        if("LF_K_i"==(*_i)->name){LF_K_i = boost::any_cast<double>(val);}
        if("LF_K_d"==(*_i)->name){LF_K_d = boost::any_cast<double>(val);}
        if("LF_windup_limit"==(*_i)->name){LF_windup_limit = boost::any_cast<double>(val);}
        if("target_distance"==(*_i)->name){target_distance = boost::any_cast<double>(val);}
        if("BD_K_p"==(*_i)->name){BD_K_p = boost::any_cast<double>(val);}
        if("BD_K_i"==(*_i)->name){BD_K_i = boost::any_cast<double>(val);}
        if("BD_K_d"==(*_i)->name){BD_K_d = boost::any_cast<double>(val);}
        if("BD_windup_limit"==(*_i)->name){BD_windup_limit = boost::any_cast<double>(val);}
        if("BD_deadzone"==(*_i)->name){BD_deadzone = boost::any_cast<double>(val);}
      }
    }

    double max_velocity;
double max_turn_rate;
int line_row_location;
double LF_K_p;
double LF_K_i;
double LF_K_d;
double LF_windup_limit;
double target_distance;
double BD_K_p;
double BD_K_i;
double BD_K_d;
double BD_windup_limit;
double BD_deadzone;

    bool state;
    std::string name;

    
}groups;



//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double max_velocity;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double max_turn_rate;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int line_row_location;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double LF_K_p;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double LF_K_i;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double LF_K_d;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double LF_windup_limit;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double target_distance;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double BD_K_p;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double BD_K_i;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double BD_K_d;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double BD_windup_limit;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double BD_deadzone;
//#line 218 "/opt/ros/kinetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();

      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        if ((*i)->fromMessage(msg, *this))
          count++;

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i ++)
      {
        if ((*i)->id == 0)
        {
          boost::any n = boost::any(this);
          (*i)->updateParams(n, *this);
          (*i)->fromMessage(msg, n);
        }
      }

      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("ReflekteServerConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__, const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toMessage(msg, *this);

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        if((*i)->id == 0)
        {
          (*i)->toMessage(msg, *this);
        }
      }
    }
    
    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      __toMessage__(msg, __param_descriptions__, __group_descriptions__);
    }
    
    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      static bool setup=false;

      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->fromServer(nh, *this);

      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++){
        if (!setup && (*i)->id == 0) {
          setup = true;
          boost::any n = boost::any(this);
          (*i)->setInitialState(n);
        }
      }
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const ReflekteServerConfig &__max__ = __getMax__();
      const ReflekteServerConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const ReflekteServerConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->calcLevel(level, config, *this);
      return level;
    }
    
    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const ReflekteServerConfig &__getDefault__();
    static const ReflekteServerConfig &__getMax__();
    static const ReflekteServerConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    static const std::vector<AbstractGroupDescriptionConstPtr> &__getGroupDescriptions__();
    
  private:
    static const ReflekteServerConfigStatics *__get_statics__();
  };
  
  template <> // Max and min are ignored for strings.
  inline void ReflekteServerConfig::ParamDescription<std::string>::clamp(ReflekteServerConfig &config, const ReflekteServerConfig &max, const ReflekteServerConfig &min) const
  {
    (void) config;
    (void) min;
    (void) max;
    return;
  }

  class ReflekteServerConfigStatics
  {
    friend class ReflekteServerConfig;
    
    ReflekteServerConfigStatics()
    {
ReflekteServerConfig::GroupDescription<ReflekteServerConfig::DEFAULT, ReflekteServerConfig> Default("Default", "", 0, 0, true, &ReflekteServerConfig::groups);
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.max_velocity = 0.0;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.max_velocity = 2.0;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.max_velocity = 0.3;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ReflekteServerConfig::AbstractParamDescriptionConstPtr(new ReflekteServerConfig::ParamDescription<double>("max_velocity", "double", 0, "The maximum velocity", "", &ReflekteServerConfig::max_velocity)));
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ReflekteServerConfig::AbstractParamDescriptionConstPtr(new ReflekteServerConfig::ParamDescription<double>("max_velocity", "double", 0, "The maximum velocity", "", &ReflekteServerConfig::max_velocity)));
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.max_turn_rate = 0.0;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.max_turn_rate = 10.0;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.max_turn_rate = 4.0;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ReflekteServerConfig::AbstractParamDescriptionConstPtr(new ReflekteServerConfig::ParamDescription<double>("max_turn_rate", "double", 0, "The maximum turn rate", "", &ReflekteServerConfig::max_turn_rate)));
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ReflekteServerConfig::AbstractParamDescriptionConstPtr(new ReflekteServerConfig::ParamDescription<double>("max_turn_rate", "double", 0, "The maximum turn rate", "", &ReflekteServerConfig::max_turn_rate)));
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.line_row_location = 0;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.line_row_location = 480;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.line_row_location = 230;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ReflekteServerConfig::AbstractParamDescriptionConstPtr(new ReflekteServerConfig::ParamDescription<int>("line_row_location", "int", 0, "Location where to look for the line that should be followed.", "", &ReflekteServerConfig::line_row_location)));
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ReflekteServerConfig::AbstractParamDescriptionConstPtr(new ReflekteServerConfig::ParamDescription<int>("line_row_location", "int", 0, "Location where to look for the line that should be followed.", "", &ReflekteServerConfig::line_row_location)));
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.LF_K_p = 0.0;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.LF_K_p = 1.0;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.LF_K_p = 0.32;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ReflekteServerConfig::AbstractParamDescriptionConstPtr(new ReflekteServerConfig::ParamDescription<double>("LF_K_p", "double", 0, "Proportional component for the line-folling PID-controller", "", &ReflekteServerConfig::LF_K_p)));
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ReflekteServerConfig::AbstractParamDescriptionConstPtr(new ReflekteServerConfig::ParamDescription<double>("LF_K_p", "double", 0, "Proportional component for the line-folling PID-controller", "", &ReflekteServerConfig::LF_K_p)));
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.LF_K_i = 0.0;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.LF_K_i = 1.0;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.LF_K_i = 0.002;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ReflekteServerConfig::AbstractParamDescriptionConstPtr(new ReflekteServerConfig::ParamDescription<double>("LF_K_i", "double", 0, "Integral component for the line-folling PID-controller", "", &ReflekteServerConfig::LF_K_i)));
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ReflekteServerConfig::AbstractParamDescriptionConstPtr(new ReflekteServerConfig::ParamDescription<double>("LF_K_i", "double", 0, "Integral component for the line-folling PID-controller", "", &ReflekteServerConfig::LF_K_i)));
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.LF_K_d = 0.0;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.LF_K_d = 1.0;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.LF_K_d = 0.09;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ReflekteServerConfig::AbstractParamDescriptionConstPtr(new ReflekteServerConfig::ParamDescription<double>("LF_K_d", "double", 0, "Derivative component for the line-folling PID-controller", "", &ReflekteServerConfig::LF_K_d)));
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ReflekteServerConfig::AbstractParamDescriptionConstPtr(new ReflekteServerConfig::ParamDescription<double>("LF_K_d", "double", 0, "Derivative component for the line-folling PID-controller", "", &ReflekteServerConfig::LF_K_d)));
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.LF_windup_limit = 0.0;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.LF_windup_limit = 5.0;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.LF_windup_limit = 0.8;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ReflekteServerConfig::AbstractParamDescriptionConstPtr(new ReflekteServerConfig::ParamDescription<double>("LF_windup_limit", "double", 0, "Limits the absolute value of the integral term of the line-following PID-controller.", "", &ReflekteServerConfig::LF_windup_limit)));
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ReflekteServerConfig::AbstractParamDescriptionConstPtr(new ReflekteServerConfig::ParamDescription<double>("LF_windup_limit", "double", 0, "Limits the absolute value of the integral term of the line-following PID-controller.", "", &ReflekteServerConfig::LF_windup_limit)));
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.target_distance = 0.0;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.target_distance = 50.0;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.target_distance = 15.0;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ReflekteServerConfig::AbstractParamDescriptionConstPtr(new ReflekteServerConfig::ParamDescription<double>("target_distance", "double", 0, "The target distance of the robot", "", &ReflekteServerConfig::target_distance)));
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ReflekteServerConfig::AbstractParamDescriptionConstPtr(new ReflekteServerConfig::ParamDescription<double>("target_distance", "double", 0, "The target distance of the robot", "", &ReflekteServerConfig::target_distance)));
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.BD_K_p = 0.0;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.BD_K_p = 1.0;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.BD_K_p = 0.03;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ReflekteServerConfig::AbstractParamDescriptionConstPtr(new ReflekteServerConfig::ParamDescription<double>("BD_K_p", "double", 0, "Proportional component for the blob-distance PID-controller", "", &ReflekteServerConfig::BD_K_p)));
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ReflekteServerConfig::AbstractParamDescriptionConstPtr(new ReflekteServerConfig::ParamDescription<double>("BD_K_p", "double", 0, "Proportional component for the blob-distance PID-controller", "", &ReflekteServerConfig::BD_K_p)));
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.BD_K_i = 0.0;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.BD_K_i = 1.0;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.BD_K_i = 0.00016;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ReflekteServerConfig::AbstractParamDescriptionConstPtr(new ReflekteServerConfig::ParamDescription<double>("BD_K_i", "double", 0, "Integral component for the blob-distance PID-controller", "", &ReflekteServerConfig::BD_K_i)));
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ReflekteServerConfig::AbstractParamDescriptionConstPtr(new ReflekteServerConfig::ParamDescription<double>("BD_K_i", "double", 0, "Integral component for the blob-distance PID-controller", "", &ReflekteServerConfig::BD_K_i)));
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.BD_K_d = 0.0;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.BD_K_d = 1.0;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.BD_K_d = 0.0013;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ReflekteServerConfig::AbstractParamDescriptionConstPtr(new ReflekteServerConfig::ParamDescription<double>("BD_K_d", "double", 0, "Derivative component for the blob-distance PID-controller", "", &ReflekteServerConfig::BD_K_d)));
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ReflekteServerConfig::AbstractParamDescriptionConstPtr(new ReflekteServerConfig::ParamDescription<double>("BD_K_d", "double", 0, "Derivative component for the blob-distance PID-controller", "", &ReflekteServerConfig::BD_K_d)));
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.BD_windup_limit = 0.0;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.BD_windup_limit = 5.0;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.BD_windup_limit = 1.5;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ReflekteServerConfig::AbstractParamDescriptionConstPtr(new ReflekteServerConfig::ParamDescription<double>("BD_windup_limit", "double", 0, "Limits the absolute value of the integral term of the blob-distance PID-controller.", "", &ReflekteServerConfig::BD_windup_limit)));
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ReflekteServerConfig::AbstractParamDescriptionConstPtr(new ReflekteServerConfig::ParamDescription<double>("BD_windup_limit", "double", 0, "Limits the absolute value of the integral term of the blob-distance PID-controller.", "", &ReflekteServerConfig::BD_windup_limit)));
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.BD_deadzone = 0.0;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.BD_deadzone = 1.0;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.BD_deadzone = 0.03;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ReflekteServerConfig::AbstractParamDescriptionConstPtr(new ReflekteServerConfig::ParamDescription<double>("BD_deadzone", "double", 0, "The deadzone used for keeping the blob distance.", "", &ReflekteServerConfig::BD_deadzone)));
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ReflekteServerConfig::AbstractParamDescriptionConstPtr(new ReflekteServerConfig::ParamDescription<double>("BD_deadzone", "double", 0, "The deadzone used for keeping the blob distance.", "", &ReflekteServerConfig::BD_deadzone)));
//#line 246 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.convertParams();
//#line 246 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(ReflekteServerConfig::AbstractGroupDescriptionConstPtr(new ReflekteServerConfig::GroupDescription<ReflekteServerConfig::DEFAULT, ReflekteServerConfig>(Default)));
//#line 356 "/opt/ros/kinetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

      for (std::vector<ReflekteServerConfig::AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        __description_message__.groups.push_back(**i);
      }
      __max__.__toMessage__(__description_message__.max, __param_descriptions__, __group_descriptions__); 
      __min__.__toMessage__(__description_message__.min, __param_descriptions__, __group_descriptions__); 
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__, __group_descriptions__); 
    }
    std::vector<ReflekteServerConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    std::vector<ReflekteServerConfig::AbstractGroupDescriptionConstPtr> __group_descriptions__;
    ReflekteServerConfig __max__;
    ReflekteServerConfig __min__;
    ReflekteServerConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;

    static const ReflekteServerConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static ReflekteServerConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &ReflekteServerConfig::__getDescriptionMessage__() 
  {
    return __get_statics__()->__description_message__;
  }

  inline const ReflekteServerConfig &ReflekteServerConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }
  
  inline const ReflekteServerConfig &ReflekteServerConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }
  
  inline const ReflekteServerConfig &ReflekteServerConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }
  
  inline const std::vector<ReflekteServerConfig::AbstractParamDescriptionConstPtr> &ReflekteServerConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const std::vector<ReflekteServerConfig::AbstractGroupDescriptionConstPtr> &ReflekteServerConfig::__getGroupDescriptions__()
  {
    return __get_statics__()->__group_descriptions__;
  }

  inline const ReflekteServerConfigStatics *ReflekteServerConfig::__get_statics__()
  {
    const static ReflekteServerConfigStatics *statics;
  
    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = ReflekteServerConfigStatics::get_instance();
    
    return statics;
  }


}

#endif // __REFLEKTESERVERRECONFIGURATOR_H__
