// Generated by gencpp from file cooperative_driving_logic/ReflekteState.msg
// DO NOT EDIT!


#ifndef COOPERATIVE_DRIVING_LOGIC_MESSAGE_REFLEKTESTATE_H
#define COOPERATIVE_DRIVING_LOGIC_MESSAGE_REFLEKTESTATE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace cooperative_driving_logic
{
template <class ContainerAllocator>
struct ReflekteState_
{
  typedef ReflekteState_<ContainerAllocator> Type;

  ReflekteState_()
    : state()
    , node_to_follow(0)  {
    }
  ReflekteState_(const ContainerAllocator& _alloc)
    : state(_alloc)
    , node_to_follow(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _state_type;
  _state_type state;

   typedef int8_t _node_to_follow_type;
  _node_to_follow_type node_to_follow;




  typedef boost::shared_ptr< ::cooperative_driving_logic::ReflekteState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cooperative_driving_logic::ReflekteState_<ContainerAllocator> const> ConstPtr;

}; // struct ReflekteState_

typedef ::cooperative_driving_logic::ReflekteState_<std::allocator<void> > ReflekteState;

typedef boost::shared_ptr< ::cooperative_driving_logic::ReflekteState > ReflekteStatePtr;
typedef boost::shared_ptr< ::cooperative_driving_logic::ReflekteState const> ReflekteStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cooperative_driving_logic::ReflekteState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cooperative_driving_logic::ReflekteState_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace cooperative_driving_logic

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'cooperative_driving_logic': ['/home/amjad/Desktop/pg2017w/ros/src/cooperative_driving/cooperative_driving_logic/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::cooperative_driving_logic::ReflekteState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cooperative_driving_logic::ReflekteState_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cooperative_driving_logic::ReflekteState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cooperative_driving_logic::ReflekteState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cooperative_driving_logic::ReflekteState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cooperative_driving_logic::ReflekteState_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cooperative_driving_logic::ReflekteState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "43cc3c773585d3b826a620cbff7f3808";
  }

  static const char* value(const ::cooperative_driving_logic::ReflekteState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x43cc3c773585d3b8ULL;
  static const uint64_t static_value2 = 0x26a620cbff7f3808ULL;
};

template<class ContainerAllocator>
struct DataType< ::cooperative_driving_logic::ReflekteState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cooperative_driving_logic/ReflekteState";
  }

  static const char* value(const ::cooperative_driving_logic::ReflekteState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cooperative_driving_logic::ReflekteState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Used to publish the current state of the reactive behavior in the Reflekte node\n\
\n\
# The current state of the reactive behavior\n\
string state\n\
int8 node_to_follow\n\
";
  }

  static const char* value(const ::cooperative_driving_logic::ReflekteState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cooperative_driving_logic::ReflekteState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.state);
      stream.next(m.node_to_follow);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ReflekteState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cooperative_driving_logic::ReflekteState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cooperative_driving_logic::ReflekteState_<ContainerAllocator>& v)
  {
    s << indent << "state: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.state);
    s << indent << "node_to_follow: ";
    Printer<int8_t>::stream(s, indent + "  ", v.node_to_follow);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COOPERATIVE_DRIVING_LOGIC_MESSAGE_REFLEKTESTATE_H
