// Generated by gencpp from file cooperative_driving_networking/BroadcastMessageResponse.msg
// DO NOT EDIT!


#ifndef COOPERATIVE_DRIVING_NETWORKING_MESSAGE_BROADCASTMESSAGERESPONSE_H
#define COOPERATIVE_DRIVING_NETWORKING_MESSAGE_BROADCASTMESSAGERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace cooperative_driving_networking
{
template <class ContainerAllocator>
struct BroadcastMessageResponse_
{
  typedef BroadcastMessageResponse_<ContainerAllocator> Type;

  BroadcastMessageResponse_()
    {
    }
  BroadcastMessageResponse_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }






  typedef boost::shared_ptr< ::cooperative_driving_networking::BroadcastMessageResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cooperative_driving_networking::BroadcastMessageResponse_<ContainerAllocator> const> ConstPtr;

}; // struct BroadcastMessageResponse_

typedef ::cooperative_driving_networking::BroadcastMessageResponse_<std::allocator<void> > BroadcastMessageResponse;

typedef boost::shared_ptr< ::cooperative_driving_networking::BroadcastMessageResponse > BroadcastMessageResponsePtr;
typedef boost::shared_ptr< ::cooperative_driving_networking::BroadcastMessageResponse const> BroadcastMessageResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cooperative_driving_networking::BroadcastMessageResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cooperative_driving_networking::BroadcastMessageResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace cooperative_driving_networking

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'cooperative_driving_networking': ['/home/amjad/Desktop/pg2017w/ros/src/cooperative_driving/cooperative_driving_networking/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::cooperative_driving_networking::BroadcastMessageResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cooperative_driving_networking::BroadcastMessageResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cooperative_driving_networking::BroadcastMessageResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cooperative_driving_networking::BroadcastMessageResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cooperative_driving_networking::BroadcastMessageResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cooperative_driving_networking::BroadcastMessageResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cooperative_driving_networking::BroadcastMessageResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::cooperative_driving_networking::BroadcastMessageResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::cooperative_driving_networking::BroadcastMessageResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cooperative_driving_networking/BroadcastMessageResponse";
  }

  static const char* value(const ::cooperative_driving_networking::BroadcastMessageResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cooperative_driving_networking::BroadcastMessageResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
";
  }

  static const char* value(const ::cooperative_driving_networking::BroadcastMessageResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cooperative_driving_networking::BroadcastMessageResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BroadcastMessageResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cooperative_driving_networking::BroadcastMessageResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::cooperative_driving_networking::BroadcastMessageResponse_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // COOPERATIVE_DRIVING_NETWORKING_MESSAGE_BROADCASTMESSAGERESPONSE_H
