// Generated by gencpp from file cooperative_driving_networking/BroadcastMessage.msg
// DO NOT EDIT!


#ifndef COOPERATIVE_DRIVING_NETWORKING_MESSAGE_BROADCASTMESSAGE_H
#define COOPERATIVE_DRIVING_NETWORKING_MESSAGE_BROADCASTMESSAGE_H

#include <ros/service_traits.h>


#include <cooperative_driving_networking/BroadcastMessageRequest.h>
#include <cooperative_driving_networking/BroadcastMessageResponse.h>


namespace cooperative_driving_networking
{

struct BroadcastMessage
{

typedef BroadcastMessageRequest Request;
typedef BroadcastMessageResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct BroadcastMessage
} // namespace cooperative_driving_networking


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::cooperative_driving_networking::BroadcastMessage > {
  static const char* value()
  {
    return "7d96ed730776804754140b85e64c862e";
  }

  static const char* value(const ::cooperative_driving_networking::BroadcastMessage&) { return value(); }
};

template<>
struct DataType< ::cooperative_driving_networking::BroadcastMessage > {
  static const char* value()
  {
    return "cooperative_driving_networking/BroadcastMessage";
  }

  static const char* value(const ::cooperative_driving_networking::BroadcastMessage&) { return value(); }
};


// service_traits::MD5Sum< ::cooperative_driving_networking::BroadcastMessageRequest> should match 
// service_traits::MD5Sum< ::cooperative_driving_networking::BroadcastMessage > 
template<>
struct MD5Sum< ::cooperative_driving_networking::BroadcastMessageRequest>
{
  static const char* value()
  {
    return MD5Sum< ::cooperative_driving_networking::BroadcastMessage >::value();
  }
  static const char* value(const ::cooperative_driving_networking::BroadcastMessageRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::cooperative_driving_networking::BroadcastMessageRequest> should match 
// service_traits::DataType< ::cooperative_driving_networking::BroadcastMessage > 
template<>
struct DataType< ::cooperative_driving_networking::BroadcastMessageRequest>
{
  static const char* value()
  {
    return DataType< ::cooperative_driving_networking::BroadcastMessage >::value();
  }
  static const char* value(const ::cooperative_driving_networking::BroadcastMessageRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::cooperative_driving_networking::BroadcastMessageResponse> should match 
// service_traits::MD5Sum< ::cooperative_driving_networking::BroadcastMessage > 
template<>
struct MD5Sum< ::cooperative_driving_networking::BroadcastMessageResponse>
{
  static const char* value()
  {
    return MD5Sum< ::cooperative_driving_networking::BroadcastMessage >::value();
  }
  static const char* value(const ::cooperative_driving_networking::BroadcastMessageResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::cooperative_driving_networking::BroadcastMessageResponse> should match 
// service_traits::DataType< ::cooperative_driving_networking::BroadcastMessage > 
template<>
struct DataType< ::cooperative_driving_networking::BroadcastMessageResponse>
{
  static const char* value()
  {
    return DataType< ::cooperative_driving_networking::BroadcastMessage >::value();
  }
  static const char* value(const ::cooperative_driving_networking::BroadcastMessageResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // COOPERATIVE_DRIVING_NETWORKING_MESSAGE_BROADCASTMESSAGE_H
