// Generated by gencpp from file cooperative_driving_networking/CooperativeAwarenessMessage.msg
// DO NOT EDIT!


#ifndef COOPERATIVE_DRIVING_NETWORKING_MESSAGE_COOPERATIVEAWARENESSMESSAGE_H
#define COOPERATIVE_DRIVING_NETWORKING_MESSAGE_COOPERATIVEAWARENESSMESSAGE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace cooperative_driving_networking
{
template <class ContainerAllocator>
struct CooperativeAwarenessMessage_
{
  typedef CooperativeAwarenessMessage_<ContainerAllocator> Type;

  CooperativeAwarenessMessage_()
    : header()
    , message_id(0)
    , sender_id(0)
    , velocity(0.0)
    , steering(0.0)
    , posx(0.0)
    , posy(0.0)
    , posz(0.0)
    , road_id(0)
    , lane_id(0)  {
    }
  CooperativeAwarenessMessage_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , message_id(0)
    , sender_id(0)
    , velocity(0.0)
    , steering(0.0)
    , posx(0.0)
    , posy(0.0)
    , posz(0.0)
    , road_id(0)
    , lane_id(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint32_t _message_id_type;
  _message_id_type message_id;

   typedef uint8_t _sender_id_type;
  _sender_id_type sender_id;

   typedef float _velocity_type;
  _velocity_type velocity;

   typedef float _steering_type;
  _steering_type steering;

   typedef float _posx_type;
  _posx_type posx;

   typedef float _posy_type;
  _posy_type posy;

   typedef float _posz_type;
  _posz_type posz;

   typedef uint8_t _road_id_type;
  _road_id_type road_id;

   typedef uint8_t _lane_id_type;
  _lane_id_type lane_id;




  typedef boost::shared_ptr< ::cooperative_driving_networking::CooperativeAwarenessMessage_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cooperative_driving_networking::CooperativeAwarenessMessage_<ContainerAllocator> const> ConstPtr;

}; // struct CooperativeAwarenessMessage_

typedef ::cooperative_driving_networking::CooperativeAwarenessMessage_<std::allocator<void> > CooperativeAwarenessMessage;

typedef boost::shared_ptr< ::cooperative_driving_networking::CooperativeAwarenessMessage > CooperativeAwarenessMessagePtr;
typedef boost::shared_ptr< ::cooperative_driving_networking::CooperativeAwarenessMessage const> CooperativeAwarenessMessageConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cooperative_driving_networking::CooperativeAwarenessMessage_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cooperative_driving_networking::CooperativeAwarenessMessage_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace cooperative_driving_networking

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'cooperative_driving_networking': ['/home/amjad/Desktop/pg2017w/ros/src/cooperative_driving/cooperative_driving_networking/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::cooperative_driving_networking::CooperativeAwarenessMessage_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cooperative_driving_networking::CooperativeAwarenessMessage_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cooperative_driving_networking::CooperativeAwarenessMessage_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cooperative_driving_networking::CooperativeAwarenessMessage_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cooperative_driving_networking::CooperativeAwarenessMessage_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cooperative_driving_networking::CooperativeAwarenessMessage_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cooperative_driving_networking::CooperativeAwarenessMessage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "55c0c4a0b38cbbc32116f929677739b2";
  }

  static const char* value(const ::cooperative_driving_networking::CooperativeAwarenessMessage_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x55c0c4a0b38cbbc3ULL;
  static const uint64_t static_value2 = 0x2116f929677739b2ULL;
};

template<class ContainerAllocator>
struct DataType< ::cooperative_driving_networking::CooperativeAwarenessMessage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cooperative_driving_networking/CooperativeAwarenessMessage";
  }

  static const char* value(const ::cooperative_driving_networking::CooperativeAwarenessMessage_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cooperative_driving_networking::CooperativeAwarenessMessage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Used in the application base class to represent a simple ETSI like CAMs\n\
\n\
# Common message header\n\
# Standard ROS message header\n\
Header header\n\
# Applicationwise uniquie identifier of this message content\n\
uint32 message_id\n\
# The id of the robot which sends this message\n\
uint8 sender_id\n\
# Specific data of this message type\n\
# The current velocity value of this robot\n\
float32 velocity\n\
# The current steering value of this robot\n\
float32 steering\n\
# The current x coordinate of this robot\n\
float32 posx\n\
# The current y coordinate of this robot\n\
float32 posy\n\
# The current z coordinate of this robot\n\
float32 posz\n\
# The id of the road this robot is currently driving on\n\
uint8 road_id\n\
# The id of the lane this robot is currently driving on\n\
uint8 lane_id\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::cooperative_driving_networking::CooperativeAwarenessMessage_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cooperative_driving_networking::CooperativeAwarenessMessage_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.message_id);
      stream.next(m.sender_id);
      stream.next(m.velocity);
      stream.next(m.steering);
      stream.next(m.posx);
      stream.next(m.posy);
      stream.next(m.posz);
      stream.next(m.road_id);
      stream.next(m.lane_id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CooperativeAwarenessMessage_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cooperative_driving_networking::CooperativeAwarenessMessage_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cooperative_driving_networking::CooperativeAwarenessMessage_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "message_id: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.message_id);
    s << indent << "sender_id: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.sender_id);
    s << indent << "velocity: ";
    Printer<float>::stream(s, indent + "  ", v.velocity);
    s << indent << "steering: ";
    Printer<float>::stream(s, indent + "  ", v.steering);
    s << indent << "posx: ";
    Printer<float>::stream(s, indent + "  ", v.posx);
    s << indent << "posy: ";
    Printer<float>::stream(s, indent + "  ", v.posy);
    s << indent << "posz: ";
    Printer<float>::stream(s, indent + "  ", v.posz);
    s << indent << "road_id: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.road_id);
    s << indent << "lane_id: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.lane_id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COOPERATIVE_DRIVING_NETWORKING_MESSAGE_COOPERATIVEAWARENESSMESSAGE_H
