//#line 2 "/opt/ros/kinetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"
// *********************************************************
// 
// File autogenerated for the cooperative_driving_vision package 
// by the dynamic_reconfigure package.
// Please do not edit.
// 
// ********************************************************/

#ifndef __cooperative_driving_vision__FEATUREEXTRACTORSERVERCONFIG_H__
#define __cooperative_driving_vision__FEATUREEXTRACTORSERVERCONFIG_H__

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/Group.h>
#include <dynamic_reconfigure/config_init_mutex.h>
#include <boost/any.hpp>

namespace cooperative_driving_vision
{
  class FeatureExtractorServerConfigStatics;
  
  class FeatureExtractorServerConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l, 
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }
      
      virtual void clamp(FeatureExtractorServerConfig &config, const FeatureExtractorServerConfig &max, const FeatureExtractorServerConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const FeatureExtractorServerConfig &config1, const FeatureExtractorServerConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, FeatureExtractorServerConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const FeatureExtractorServerConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, FeatureExtractorServerConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const FeatureExtractorServerConfig &config) const = 0;
      virtual void getValue(const FeatureExtractorServerConfig &config, boost::any &val) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;
    
    template <class T>
    class ParamDescription : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string a_name, std::string a_type, uint32_t a_level, 
          std::string a_description, std::string a_edit_method, T FeatureExtractorServerConfig::* a_f) :
        AbstractParamDescription(a_name, a_type, a_level, a_description, a_edit_method),
        field(a_f)
      {}

      T (FeatureExtractorServerConfig::* field);

      virtual void clamp(FeatureExtractorServerConfig &config, const FeatureExtractorServerConfig &max, const FeatureExtractorServerConfig &min) const
      {
        if (config.*field > max.*field)
          config.*field = max.*field;
        
        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const FeatureExtractorServerConfig &config1, const FeatureExtractorServerConfig &config2) const
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, FeatureExtractorServerConfig &config) const
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const FeatureExtractorServerConfig &config) const
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, FeatureExtractorServerConfig &config) const
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const FeatureExtractorServerConfig &config) const
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }

      virtual void getValue(const FeatureExtractorServerConfig &config, boost::any &val) const
      {
        val = config.*field;
      }
    };

    class AbstractGroupDescription : public dynamic_reconfigure::Group
    {
      public:
      AbstractGroupDescription(std::string n, std::string t, int p, int i, bool s)
      {
        name = n;
        type = t;
        parent = p;
        state = s;
        id = i;
      }

      std::vector<AbstractParamDescriptionConstPtr> abstract_parameters;
      bool state;

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &config) const =0;
      virtual void updateParams(boost::any &cfg, FeatureExtractorServerConfig &top) const= 0;
      virtual void setInitialState(boost::any &cfg) const = 0;


      void convertParams()
      {
        for(std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = abstract_parameters.begin(); i != abstract_parameters.end(); ++i)
        {
          parameters.push_back(dynamic_reconfigure::ParamDescription(**i));
        }
      }
    };

    typedef boost::shared_ptr<AbstractGroupDescription> AbstractGroupDescriptionPtr;
    typedef boost::shared_ptr<const AbstractGroupDescription> AbstractGroupDescriptionConstPtr;

    template<class T, class PT>
    class GroupDescription : public AbstractGroupDescription
    {
    public:
      GroupDescription(std::string a_name, std::string a_type, int a_parent, int a_id, bool a_s, T PT::* a_f) : AbstractGroupDescription(a_name, a_type, a_parent, a_id, a_s), field(a_f)
      {
      }

      GroupDescription(const GroupDescription<T, PT>& g): AbstractGroupDescription(g.name, g.type, g.parent, g.id, g.state), field(g.field), groups(g.groups)
      {
        parameters = g.parameters;
        abstract_parameters = g.abstract_parameters;
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        if(!dynamic_reconfigure::ConfigTools::getGroupState(msg, name, (*config).*field))
          return false;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          if(!(*i)->fromMessage(msg, n))
            return false;
        }

        return true;
      }

      virtual void setInitialState(boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        T* group = &((*config).*field);
        group->state = state;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = boost::any(&((*config).*field));
          (*i)->setInitialState(n);
        }

      }

      virtual void updateParams(boost::any &cfg, FeatureExtractorServerConfig &top) const
      {
        PT* config = boost::any_cast<PT*>(cfg);

        T* f = &((*config).*field);
        f->setParams(top, abstract_parameters);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          (*i)->updateParams(n, top);
        }
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &cfg) const
      {
        const PT config = boost::any_cast<PT>(cfg);
        dynamic_reconfigure::ConfigTools::appendGroup<T>(msg, name, id, parent, config.*field);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          (*i)->toMessage(msg, config.*field);
        }
      }

      T (PT::* field);
      std::vector<FeatureExtractorServerConfig::AbstractGroupDescriptionConstPtr> groups;
    };
    
class DEFAULT
{
  public:
    DEFAULT()
    {
      state = true;
      name = "Default";
    }

    void setParams(FeatureExtractorServerConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("line_interval_lower_v"==(*_i)->name){line_interval_lower_v = boost::any_cast<double>(val);}
        if("line_interval_upper_v"==(*_i)->name){line_interval_upper_v = boost::any_cast<double>(val);}
        if("line_count_v"==(*_i)->name){line_count_v = boost::any_cast<int>(val);}
        if("row_influence_area_v"==(*_i)->name){row_influence_area_v = boost::any_cast<int>(val);}
        if("lower_canny_threshold_v"==(*_i)->name){lower_canny_threshold_v = boost::any_cast<int>(val);}
        if("line_interval_lower_h"==(*_i)->name){line_interval_lower_h = boost::any_cast<double>(val);}
        if("line_interval_upper_h"==(*_i)->name){line_interval_upper_h = boost::any_cast<double>(val);}
        if("line_count_h"==(*_i)->name){line_count_h = boost::any_cast<int>(val);}
        if("row_influence_area_h"==(*_i)->name){row_influence_area_h = boost::any_cast<int>(val);}
        if("lower_canny_threshold_h"==(*_i)->name){lower_canny_threshold_h = boost::any_cast<int>(val);}
        if("box_width"==(*_i)->name){box_width = boost::any_cast<double>(val);}
        if("box_height"==(*_i)->name){box_height = boost::any_cast<double>(val);}
        if("min_line_length"==(*_i)->name){min_line_length = boost::any_cast<int>(val);}
        if("min_region_size"==(*_i)->name){min_region_size = boost::any_cast<int>(val);}
      }
    }

    double line_interval_lower_v;
double line_interval_upper_v;
int line_count_v;
int row_influence_area_v;
int lower_canny_threshold_v;
double line_interval_lower_h;
double line_interval_upper_h;
int line_count_h;
int row_influence_area_h;
int lower_canny_threshold_h;
double box_width;
double box_height;
int min_line_length;
int min_region_size;

    bool state;
    std::string name;

    
}groups;



//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double line_interval_lower_v;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double line_interval_upper_v;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int line_count_v;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int row_influence_area_v;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int lower_canny_threshold_v;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double line_interval_lower_h;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double line_interval_upper_h;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int line_count_h;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int row_influence_area_h;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int lower_canny_threshold_h;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double box_width;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double box_height;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int min_line_length;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int min_region_size;
//#line 218 "/opt/ros/kinetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();

      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        if ((*i)->fromMessage(msg, *this))
          count++;

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i ++)
      {
        if ((*i)->id == 0)
        {
          boost::any n = boost::any(this);
          (*i)->updateParams(n, *this);
          (*i)->fromMessage(msg, n);
        }
      }

      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("FeatureExtractorServerConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__, const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toMessage(msg, *this);

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        if((*i)->id == 0)
        {
          (*i)->toMessage(msg, *this);
        }
      }
    }
    
    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      __toMessage__(msg, __param_descriptions__, __group_descriptions__);
    }
    
    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      static bool setup=false;

      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->fromServer(nh, *this);

      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++){
        if (!setup && (*i)->id == 0) {
          setup = true;
          boost::any n = boost::any(this);
          (*i)->setInitialState(n);
        }
      }
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const FeatureExtractorServerConfig &__max__ = __getMax__();
      const FeatureExtractorServerConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const FeatureExtractorServerConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->calcLevel(level, config, *this);
      return level;
    }
    
    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const FeatureExtractorServerConfig &__getDefault__();
    static const FeatureExtractorServerConfig &__getMax__();
    static const FeatureExtractorServerConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    static const std::vector<AbstractGroupDescriptionConstPtr> &__getGroupDescriptions__();
    
  private:
    static const FeatureExtractorServerConfigStatics *__get_statics__();
  };
  
  template <> // Max and min are ignored for strings.
  inline void FeatureExtractorServerConfig::ParamDescription<std::string>::clamp(FeatureExtractorServerConfig &config, const FeatureExtractorServerConfig &max, const FeatureExtractorServerConfig &min) const
  {
    (void) config;
    (void) min;
    (void) max;
    return;
  }

  class FeatureExtractorServerConfigStatics
  {
    friend class FeatureExtractorServerConfig;
    
    FeatureExtractorServerConfigStatics()
    {
FeatureExtractorServerConfig::GroupDescription<FeatureExtractorServerConfig::DEFAULT, FeatureExtractorServerConfig> Default("Default", "", 0, 0, true, &FeatureExtractorServerConfig::groups);
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.line_interval_lower_v = 0.0;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.line_interval_lower_v = 1.0;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.line_interval_lower_v = 0.0;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(FeatureExtractorServerConfig::AbstractParamDescriptionConstPtr(new FeatureExtractorServerConfig::ParamDescription<double>("line_interval_lower_v", "double", 0, "Lower end of normalized rows for vertical line detection", "", &FeatureExtractorServerConfig::line_interval_lower_v)));
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(FeatureExtractorServerConfig::AbstractParamDescriptionConstPtr(new FeatureExtractorServerConfig::ParamDescription<double>("line_interval_lower_v", "double", 0, "Lower end of normalized rows for vertical line detection", "", &FeatureExtractorServerConfig::line_interval_lower_v)));
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.line_interval_upper_v = 0.0;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.line_interval_upper_v = 1.0;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.line_interval_upper_v = 1.0;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(FeatureExtractorServerConfig::AbstractParamDescriptionConstPtr(new FeatureExtractorServerConfig::ParamDescription<double>("line_interval_upper_v", "double", 0, "Upper end of normalized rows for vertical line detection", "", &FeatureExtractorServerConfig::line_interval_upper_v)));
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(FeatureExtractorServerConfig::AbstractParamDescriptionConstPtr(new FeatureExtractorServerConfig::ParamDescription<double>("line_interval_upper_v", "double", 0, "Upper end of normalized rows for vertical line detection", "", &FeatureExtractorServerConfig::line_interval_upper_v)));
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.line_count_v = 1;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.line_count_v = 50;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.line_count_v = 20;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(FeatureExtractorServerConfig::AbstractParamDescriptionConstPtr(new FeatureExtractorServerConfig::ParamDescription<int>("line_count_v", "int", 0, "Number of vertical lines to extract", "", &FeatureExtractorServerConfig::line_count_v)));
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(FeatureExtractorServerConfig::AbstractParamDescriptionConstPtr(new FeatureExtractorServerConfig::ParamDescription<int>("line_count_v", "int", 0, "Number of vertical lines to extract", "", &FeatureExtractorServerConfig::line_count_v)));
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.row_influence_area_v = 1;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.row_influence_area_v = 25;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.row_influence_area_v = 5;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(FeatureExtractorServerConfig::AbstractParamDescriptionConstPtr(new FeatureExtractorServerConfig::ParamDescription<int>("row_influence_area_v", "int", 0, "Number of rows to include for vertical line detection", "", &FeatureExtractorServerConfig::row_influence_area_v)));
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(FeatureExtractorServerConfig::AbstractParamDescriptionConstPtr(new FeatureExtractorServerConfig::ParamDescription<int>("row_influence_area_v", "int", 0, "Number of rows to include for vertical line detection", "", &FeatureExtractorServerConfig::row_influence_area_v)));
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.lower_canny_threshold_v = 1;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.lower_canny_threshold_v = 100;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.lower_canny_threshold_v = 40;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(FeatureExtractorServerConfig::AbstractParamDescriptionConstPtr(new FeatureExtractorServerConfig::ParamDescription<int>("lower_canny_threshold_v", "int", 0, "The lower threshold used for the vertical canny filter (Max. Threshold is 3 times the lower threshold)", "", &FeatureExtractorServerConfig::lower_canny_threshold_v)));
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(FeatureExtractorServerConfig::AbstractParamDescriptionConstPtr(new FeatureExtractorServerConfig::ParamDescription<int>("lower_canny_threshold_v", "int", 0, "The lower threshold used for the vertical canny filter (Max. Threshold is 3 times the lower threshold)", "", &FeatureExtractorServerConfig::lower_canny_threshold_v)));
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.line_interval_lower_h = 0.0;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.line_interval_lower_h = 1.0;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.line_interval_lower_h = 0.0;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(FeatureExtractorServerConfig::AbstractParamDescriptionConstPtr(new FeatureExtractorServerConfig::ParamDescription<double>("line_interval_lower_h", "double", 0, "Lower end of normalized rows for horizontal line detection", "", &FeatureExtractorServerConfig::line_interval_lower_h)));
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(FeatureExtractorServerConfig::AbstractParamDescriptionConstPtr(new FeatureExtractorServerConfig::ParamDescription<double>("line_interval_lower_h", "double", 0, "Lower end of normalized rows for horizontal line detection", "", &FeatureExtractorServerConfig::line_interval_lower_h)));
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.line_interval_upper_h = 0.0;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.line_interval_upper_h = 1.0;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.line_interval_upper_h = 1.0;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(FeatureExtractorServerConfig::AbstractParamDescriptionConstPtr(new FeatureExtractorServerConfig::ParamDescription<double>("line_interval_upper_h", "double", 0, "Upper end of normalized rows for horizontal line detection", "", &FeatureExtractorServerConfig::line_interval_upper_h)));
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(FeatureExtractorServerConfig::AbstractParamDescriptionConstPtr(new FeatureExtractorServerConfig::ParamDescription<double>("line_interval_upper_h", "double", 0, "Upper end of normalized rows for horizontal line detection", "", &FeatureExtractorServerConfig::line_interval_upper_h)));
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.line_count_h = 1;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.line_count_h = 50;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.line_count_h = 20;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(FeatureExtractorServerConfig::AbstractParamDescriptionConstPtr(new FeatureExtractorServerConfig::ParamDescription<int>("line_count_h", "int", 0, "Number of horizontal lines to extract", "", &FeatureExtractorServerConfig::line_count_h)));
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(FeatureExtractorServerConfig::AbstractParamDescriptionConstPtr(new FeatureExtractorServerConfig::ParamDescription<int>("line_count_h", "int", 0, "Number of horizontal lines to extract", "", &FeatureExtractorServerConfig::line_count_h)));
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.row_influence_area_h = 1;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.row_influence_area_h = 25;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.row_influence_area_h = 5;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(FeatureExtractorServerConfig::AbstractParamDescriptionConstPtr(new FeatureExtractorServerConfig::ParamDescription<int>("row_influence_area_h", "int", 0, "Number of rows to include for horizontal line detection", "", &FeatureExtractorServerConfig::row_influence_area_h)));
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(FeatureExtractorServerConfig::AbstractParamDescriptionConstPtr(new FeatureExtractorServerConfig::ParamDescription<int>("row_influence_area_h", "int", 0, "Number of rows to include for horizontal line detection", "", &FeatureExtractorServerConfig::row_influence_area_h)));
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.lower_canny_threshold_h = 1;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.lower_canny_threshold_h = 100;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.lower_canny_threshold_h = 64;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(FeatureExtractorServerConfig::AbstractParamDescriptionConstPtr(new FeatureExtractorServerConfig::ParamDescription<int>("lower_canny_threshold_h", "int", 0, "The lower threshold used for the horizontal canny filter (Max. Threshold is 3 times the lower threshold)", "", &FeatureExtractorServerConfig::lower_canny_threshold_h)));
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(FeatureExtractorServerConfig::AbstractParamDescriptionConstPtr(new FeatureExtractorServerConfig::ParamDescription<int>("lower_canny_threshold_h", "int", 0, "The lower threshold used for the horizontal canny filter (Max. Threshold is 3 times the lower threshold)", "", &FeatureExtractorServerConfig::lower_canny_threshold_h)));
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.box_width = 0.0;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.box_width = 1.0;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.box_width = 0.68;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(FeatureExtractorServerConfig::AbstractParamDescriptionConstPtr(new FeatureExtractorServerConfig::ParamDescription<double>("box_width", "double", 0, "Width of the box in percentage of image width", "", &FeatureExtractorServerConfig::box_width)));
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(FeatureExtractorServerConfig::AbstractParamDescriptionConstPtr(new FeatureExtractorServerConfig::ParamDescription<double>("box_width", "double", 0, "Width of the box in percentage of image width", "", &FeatureExtractorServerConfig::box_width)));
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.box_height = 0.0;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.box_height = 1.0;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.box_height = 0.62;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(FeatureExtractorServerConfig::AbstractParamDescriptionConstPtr(new FeatureExtractorServerConfig::ParamDescription<double>("box_height", "double", 0, "Height of the box in percentage of image height", "", &FeatureExtractorServerConfig::box_height)));
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(FeatureExtractorServerConfig::AbstractParamDescriptionConstPtr(new FeatureExtractorServerConfig::ParamDescription<double>("box_height", "double", 0, "Height of the box in percentage of image height", "", &FeatureExtractorServerConfig::box_height)));
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.min_line_length = 0;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.min_line_length = 100;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.min_line_length = 4;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(FeatureExtractorServerConfig::AbstractParamDescriptionConstPtr(new FeatureExtractorServerConfig::ParamDescription<int>("min_line_length", "int", 0, "The minimum line size for detecting blobs.", "", &FeatureExtractorServerConfig::min_line_length)));
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(FeatureExtractorServerConfig::AbstractParamDescriptionConstPtr(new FeatureExtractorServerConfig::ParamDescription<int>("min_line_length", "int", 0, "The minimum line size for detecting blobs.", "", &FeatureExtractorServerConfig::min_line_length)));
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.min_region_size = 0;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.min_region_size = 800;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.min_region_size = 200;
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(FeatureExtractorServerConfig::AbstractParamDescriptionConstPtr(new FeatureExtractorServerConfig::ParamDescription<int>("min_region_size", "int", 0, "The minimum size detected regions are processed.", "", &FeatureExtractorServerConfig::min_region_size)));
//#line 293 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(FeatureExtractorServerConfig::AbstractParamDescriptionConstPtr(new FeatureExtractorServerConfig::ParamDescription<int>("min_region_size", "int", 0, "The minimum size detected regions are processed.", "", &FeatureExtractorServerConfig::min_region_size)));
//#line 246 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.convertParams();
//#line 246 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(FeatureExtractorServerConfig::AbstractGroupDescriptionConstPtr(new FeatureExtractorServerConfig::GroupDescription<FeatureExtractorServerConfig::DEFAULT, FeatureExtractorServerConfig>(Default)));
//#line 356 "/opt/ros/kinetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

      for (std::vector<FeatureExtractorServerConfig::AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        __description_message__.groups.push_back(**i);
      }
      __max__.__toMessage__(__description_message__.max, __param_descriptions__, __group_descriptions__); 
      __min__.__toMessage__(__description_message__.min, __param_descriptions__, __group_descriptions__); 
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__, __group_descriptions__); 
    }
    std::vector<FeatureExtractorServerConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    std::vector<FeatureExtractorServerConfig::AbstractGroupDescriptionConstPtr> __group_descriptions__;
    FeatureExtractorServerConfig __max__;
    FeatureExtractorServerConfig __min__;
    FeatureExtractorServerConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;

    static const FeatureExtractorServerConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static FeatureExtractorServerConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &FeatureExtractorServerConfig::__getDescriptionMessage__() 
  {
    return __get_statics__()->__description_message__;
  }

  inline const FeatureExtractorServerConfig &FeatureExtractorServerConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }
  
  inline const FeatureExtractorServerConfig &FeatureExtractorServerConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }
  
  inline const FeatureExtractorServerConfig &FeatureExtractorServerConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }
  
  inline const std::vector<FeatureExtractorServerConfig::AbstractParamDescriptionConstPtr> &FeatureExtractorServerConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const std::vector<FeatureExtractorServerConfig::AbstractGroupDescriptionConstPtr> &FeatureExtractorServerConfig::__getGroupDescriptions__()
  {
    return __get_statics__()->__group_descriptions__;
  }

  inline const FeatureExtractorServerConfigStatics *FeatureExtractorServerConfig::__get_statics__()
  {
    const static FeatureExtractorServerConfigStatics *statics;
  
    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = FeatureExtractorServerConfigStatics::get_instance();
    
    return statics;
  }


}

#endif // __FEATUREEXTRACTORSERVERRECONFIGURATOR_H__
