// Generated by gencpp from file cooperative_driving_vision/Moment.msg
// DO NOT EDIT!


#ifndef COOPERATIVE_DRIVING_VISION_MESSAGE_MOMENT_H
#define COOPERATIVE_DRIVING_VISION_MESSAGE_MOMENT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace cooperative_driving_vision
{
template <class ContainerAllocator>
struct Moment_
{
  typedef Moment_<ContainerAllocator> Type;

  Moment_()
    : m00(0.0)
    , m10(0.0)
    , m01(0.0)
    , m11(0.0)
    , m20(0.0)
    , m02(0.0)
    , m21(0.0)
    , m12(0.0)
    , m30(0.0)
    , m03(0.0)  {
    }
  Moment_(const ContainerAllocator& _alloc)
    : m00(0.0)
    , m10(0.0)
    , m01(0.0)
    , m11(0.0)
    , m20(0.0)
    , m02(0.0)
    , m21(0.0)
    , m12(0.0)
    , m30(0.0)
    , m03(0.0)  {
  (void)_alloc;
    }



   typedef float _m00_type;
  _m00_type m00;

   typedef float _m10_type;
  _m10_type m10;

   typedef float _m01_type;
  _m01_type m01;

   typedef float _m11_type;
  _m11_type m11;

   typedef float _m20_type;
  _m20_type m20;

   typedef float _m02_type;
  _m02_type m02;

   typedef float _m21_type;
  _m21_type m21;

   typedef float _m12_type;
  _m12_type m12;

   typedef float _m30_type;
  _m30_type m30;

   typedef float _m03_type;
  _m03_type m03;




  typedef boost::shared_ptr< ::cooperative_driving_vision::Moment_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cooperative_driving_vision::Moment_<ContainerAllocator> const> ConstPtr;

}; // struct Moment_

typedef ::cooperative_driving_vision::Moment_<std::allocator<void> > Moment;

typedef boost::shared_ptr< ::cooperative_driving_vision::Moment > MomentPtr;
typedef boost::shared_ptr< ::cooperative_driving_vision::Moment const> MomentConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cooperative_driving_vision::Moment_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cooperative_driving_vision::Moment_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace cooperative_driving_vision

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'cooperative_driving_vision': ['/home/amjad/Desktop/pg2017w/ros/src/cooperative_driving/cooperative_driving_vision/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::cooperative_driving_vision::Moment_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cooperative_driving_vision::Moment_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cooperative_driving_vision::Moment_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cooperative_driving_vision::Moment_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cooperative_driving_vision::Moment_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cooperative_driving_vision::Moment_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cooperative_driving_vision::Moment_<ContainerAllocator> >
{
  static const char* value()
  {
    return "15ca49fd130f761e715cfaf6f1985ad7";
  }

  static const char* value(const ::cooperative_driving_vision::Moment_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x15ca49fd130f761eULL;
  static const uint64_t static_value2 = 0x715cfaf6f1985ad7ULL;
};

template<class ContainerAllocator>
struct DataType< ::cooperative_driving_vision::Moment_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cooperative_driving_vision/Moment";
  }

  static const char* value(const ::cooperative_driving_vision::Moment_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cooperative_driving_vision::Moment_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Custom message type to represent a geometrical moment\n\
\n\
# (0, 0)th raw moment, i.e. number of pixels\n\
float32 m00\n\
# (1, 0)th raw moment\n\
float32 m10\n\
# (0, 1)th raw moment\n\
float32 m01\n\
# (1, 1)th raw moment\n\
float32 m11\n\
# (2, 0)th raw moment\n\
float32 m20\n\
# (0, 2)th raw moment\n\
float32 m02\n\
# (2, 1)th raw moment\n\
float32 m21\n\
# (1, 2)th raw moment\n\
float32 m12\n\
# (3, 0)th raw moment\n\
float32 m30\n\
# (0, 3)th raw moment\n\
float32 m03\n\
";
  }

  static const char* value(const ::cooperative_driving_vision::Moment_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cooperative_driving_vision::Moment_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.m00);
      stream.next(m.m10);
      stream.next(m.m01);
      stream.next(m.m11);
      stream.next(m.m20);
      stream.next(m.m02);
      stream.next(m.m21);
      stream.next(m.m12);
      stream.next(m.m30);
      stream.next(m.m03);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Moment_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cooperative_driving_vision::Moment_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cooperative_driving_vision::Moment_<ContainerAllocator>& v)
  {
    s << indent << "m00: ";
    Printer<float>::stream(s, indent + "  ", v.m00);
    s << indent << "m10: ";
    Printer<float>::stream(s, indent + "  ", v.m10);
    s << indent << "m01: ";
    Printer<float>::stream(s, indent + "  ", v.m01);
    s << indent << "m11: ";
    Printer<float>::stream(s, indent + "  ", v.m11);
    s << indent << "m20: ";
    Printer<float>::stream(s, indent + "  ", v.m20);
    s << indent << "m02: ";
    Printer<float>::stream(s, indent + "  ", v.m02);
    s << indent << "m21: ";
    Printer<float>::stream(s, indent + "  ", v.m21);
    s << indent << "m12: ";
    Printer<float>::stream(s, indent + "  ", v.m12);
    s << indent << "m30: ";
    Printer<float>::stream(s, indent + "  ", v.m30);
    s << indent << "m03: ";
    Printer<float>::stream(s, indent + "  ", v.m03);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COOPERATIVE_DRIVING_VISION_MESSAGE_MOMENT_H
