// Generated by gencpp from file cooperative_driving_msgs/Command.msg
// DO NOT EDIT!


#ifndef COOPERATIVE_DRIVING_MSGS_MESSAGE_COMMAND_H
#define COOPERATIVE_DRIVING_MSGS_MESSAGE_COMMAND_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <cooperative_driving_msgs/Direction.h>

namespace cooperative_driving_msgs
{
template <class ContainerAllocator>
struct Command_
{
  typedef Command_<ContainerAllocator> Type;

  Command_()
    : header()
    , message_id(0)
    , sender_id(0)
    , command()
    , turn()  {
    }
  Command_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , message_id(0)
    , sender_id(0)
    , command(_alloc)
    , turn(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint32_t _message_id_type;
  _message_id_type message_id;

   typedef uint8_t _sender_id_type;
  _sender_id_type sender_id;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _command_type;
  _command_type command;

   typedef  ::cooperative_driving_msgs::Direction_<ContainerAllocator>  _turn_type;
  _turn_type turn;




  typedef boost::shared_ptr< ::cooperative_driving_msgs::Command_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cooperative_driving_msgs::Command_<ContainerAllocator> const> ConstPtr;

}; // struct Command_

typedef ::cooperative_driving_msgs::Command_<std::allocator<void> > Command;

typedef boost::shared_ptr< ::cooperative_driving_msgs::Command > CommandPtr;
typedef boost::shared_ptr< ::cooperative_driving_msgs::Command const> CommandConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cooperative_driving_msgs::Command_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cooperative_driving_msgs::Command_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace cooperative_driving_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'cooperative_driving_msgs': ['/home/amjad/Desktop/pg2017w/ros/src/cooperative_driving/cooperative_driving_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::cooperative_driving_msgs::Command_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cooperative_driving_msgs::Command_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cooperative_driving_msgs::Command_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cooperative_driving_msgs::Command_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cooperative_driving_msgs::Command_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cooperative_driving_msgs::Command_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cooperative_driving_msgs::Command_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a2cc60514e9f00b5f108e5118c24aaa9";
  }

  static const char* value(const ::cooperative_driving_msgs::Command_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa2cc60514e9f00b5ULL;
  static const uint64_t static_value2 = 0xf108e5118c24aaa9ULL;
};

template<class ContainerAllocator>
struct DataType< ::cooperative_driving_msgs::Command_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cooperative_driving_msgs/Command";
  }

  static const char* value(const ::cooperative_driving_msgs::Command_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cooperative_driving_msgs::Command_<ContainerAllocator> >
{
  static const char* value()
  {
    return "## Command a direction change at an upcoming crossing\n\
# Common message header\n\
# Standard ROS message header\n\
Header header\n\
# Define the direction to take at the upcoming crossing\n\
uint32 message_id\n\
# The id of the robot which sends this message\n\
uint8 sender_id\n\
# Specific data of this message type\n\
\n\
# Commnand to be executed\n\
string command\n\
# Parameters for the command\n\
\n\
# Parameter for turn command\n\
Direction turn\n\
\n\
#TODO: Add other command parameters here\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: cooperative_driving_msgs/Direction\n\
## Define a direction of a detected crossing, i.e., a turn that can possibly be taken\n\
\n\
# Possible turn at a crossing ('straight', 'left', or 'right')\n\
string direction\n\
";
  }

  static const char* value(const ::cooperative_driving_msgs::Command_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cooperative_driving_msgs::Command_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.message_id);
      stream.next(m.sender_id);
      stream.next(m.command);
      stream.next(m.turn);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Command_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cooperative_driving_msgs::Command_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cooperative_driving_msgs::Command_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "message_id: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.message_id);
    s << indent << "sender_id: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.sender_id);
    s << indent << "command: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.command);
    s << indent << "turn: ";
    s << std::endl;
    Printer< ::cooperative_driving_msgs::Direction_<ContainerAllocator> >::stream(s, indent + "  ", v.turn);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COOPERATIVE_DRIVING_MSGS_MESSAGE_COMMAND_H
