// Generated by gencpp from file cooperative_driving_msgs/Direction.msg
// DO NOT EDIT!


#ifndef COOPERATIVE_DRIVING_MSGS_MESSAGE_DIRECTION_H
#define COOPERATIVE_DRIVING_MSGS_MESSAGE_DIRECTION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace cooperative_driving_msgs
{
template <class ContainerAllocator>
struct Direction_
{
  typedef Direction_<ContainerAllocator> Type;

  Direction_()
    : direction()  {
    }
  Direction_(const ContainerAllocator& _alloc)
    : direction(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _direction_type;
  _direction_type direction;




  typedef boost::shared_ptr< ::cooperative_driving_msgs::Direction_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cooperative_driving_msgs::Direction_<ContainerAllocator> const> ConstPtr;

}; // struct Direction_

typedef ::cooperative_driving_msgs::Direction_<std::allocator<void> > Direction;

typedef boost::shared_ptr< ::cooperative_driving_msgs::Direction > DirectionPtr;
typedef boost::shared_ptr< ::cooperative_driving_msgs::Direction const> DirectionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cooperative_driving_msgs::Direction_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cooperative_driving_msgs::Direction_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace cooperative_driving_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'cooperative_driving_msgs': ['/home/amjad/Desktop/pg2017w/ros/src/cooperative_driving/cooperative_driving_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::cooperative_driving_msgs::Direction_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cooperative_driving_msgs::Direction_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cooperative_driving_msgs::Direction_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cooperative_driving_msgs::Direction_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cooperative_driving_msgs::Direction_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cooperative_driving_msgs::Direction_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cooperative_driving_msgs::Direction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "326e9417def5db9a05a2704a4d8de15e";
  }

  static const char* value(const ::cooperative_driving_msgs::Direction_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x326e9417def5db9aULL;
  static const uint64_t static_value2 = 0x05a2704a4d8de15eULL;
};

template<class ContainerAllocator>
struct DataType< ::cooperative_driving_msgs::Direction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cooperative_driving_msgs/Direction";
  }

  static const char* value(const ::cooperative_driving_msgs::Direction_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cooperative_driving_msgs::Direction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "## Define a direction of a detected crossing, i.e., a turn that can possibly be taken\n\
\n\
# Possible turn at a crossing ('straight', 'left', or 'right')\n\
string direction\n\
";
  }

  static const char* value(const ::cooperative_driving_msgs::Direction_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cooperative_driving_msgs::Direction_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.direction);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Direction_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cooperative_driving_msgs::Direction_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cooperative_driving_msgs::Direction_<ContainerAllocator>& v)
  {
    s << indent << "direction: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.direction);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COOPERATIVE_DRIVING_MSGS_MESSAGE_DIRECTION_H
