// Generated by gencpp from file cooperative_driving_hardware/LedCommand.msg
// DO NOT EDIT!


#ifndef COOPERATIVE_DRIVING_HARDWARE_MESSAGE_LEDCOMMAND_H
#define COOPERATIVE_DRIVING_HARDWARE_MESSAGE_LEDCOMMAND_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <cooperative_driving_hardware/LedValue.h>

namespace cooperative_driving_hardware
{
template <class ContainerAllocator>
struct LedCommand_
{
  typedef LedCommand_<ContainerAllocator> Type;

  LedCommand_()
    : header()
    , values()  {
    }
  LedCommand_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , values(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::cooperative_driving_hardware::LedValue_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::cooperative_driving_hardware::LedValue_<ContainerAllocator> >::other >  _values_type;
  _values_type values;




  typedef boost::shared_ptr< ::cooperative_driving_hardware::LedCommand_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cooperative_driving_hardware::LedCommand_<ContainerAllocator> const> ConstPtr;

}; // struct LedCommand_

typedef ::cooperative_driving_hardware::LedCommand_<std::allocator<void> > LedCommand;

typedef boost::shared_ptr< ::cooperative_driving_hardware::LedCommand > LedCommandPtr;
typedef boost::shared_ptr< ::cooperative_driving_hardware::LedCommand const> LedCommandConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cooperative_driving_hardware::LedCommand_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cooperative_driving_hardware::LedCommand_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace cooperative_driving_hardware

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'cooperative_driving_hardware': ['/home/amjad/Desktop/pg2017w/ros/src/cooperative_driving/cooperative_driving_hardware/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::cooperative_driving_hardware::LedCommand_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cooperative_driving_hardware::LedCommand_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cooperative_driving_hardware::LedCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cooperative_driving_hardware::LedCommand_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cooperative_driving_hardware::LedCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cooperative_driving_hardware::LedCommand_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cooperative_driving_hardware::LedCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7149f6e7328bbb637f466762bbc9f089";
  }

  static const char* value(const ::cooperative_driving_hardware::LedCommand_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7149f6e7328bbb63ULL;
  static const uint64_t static_value2 = 0x7f466762bbc9f089ULL;
};

template<class ContainerAllocator>
struct DataType< ::cooperative_driving_hardware::LedCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cooperative_driving_hardware/LedCommand";
  }

  static const char* value(const ::cooperative_driving_hardware::LedCommand_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cooperative_driving_hardware::LedCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Used for flashing LEDs\n\
\n\
# Standard ROS message header\n\
Header header\n\
# An array of LedValue messages which represent the LED values to set\n\
LedValue[] values\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: cooperative_driving_hardware/LedValue\n\
# Custom message type represent a reading from a distance sensor used for reading and writing\n\
\n\
# The frame_id (name) of this LED\n\
string frame_id\n\
# The current value of this LED\n\
# Values in [0, 1]\n\
float32 value\n\
";
  }

  static const char* value(const ::cooperative_driving_hardware::LedCommand_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cooperative_driving_hardware::LedCommand_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.values);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LedCommand_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cooperative_driving_hardware::LedCommand_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cooperative_driving_hardware::LedCommand_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "values[]" << std::endl;
    for (size_t i = 0; i < v.values.size(); ++i)
    {
      s << indent << "  values[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::cooperative_driving_hardware::LedValue_<ContainerAllocator> >::stream(s, indent + "    ", v.values[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // COOPERATIVE_DRIVING_HARDWARE_MESSAGE_LEDCOMMAND_H
