// Generated by gencpp from file cooperative_driving_hardware/LedValue.msg
// DO NOT EDIT!


#ifndef COOPERATIVE_DRIVING_HARDWARE_MESSAGE_LEDVALUE_H
#define COOPERATIVE_DRIVING_HARDWARE_MESSAGE_LEDVALUE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace cooperative_driving_hardware
{
template <class ContainerAllocator>
struct LedValue_
{
  typedef LedValue_<ContainerAllocator> Type;

  LedValue_()
    : frame_id()
    , value(0.0)  {
    }
  LedValue_(const ContainerAllocator& _alloc)
    : frame_id(_alloc)
    , value(0.0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _frame_id_type;
  _frame_id_type frame_id;

   typedef float _value_type;
  _value_type value;




  typedef boost::shared_ptr< ::cooperative_driving_hardware::LedValue_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cooperative_driving_hardware::LedValue_<ContainerAllocator> const> ConstPtr;

}; // struct LedValue_

typedef ::cooperative_driving_hardware::LedValue_<std::allocator<void> > LedValue;

typedef boost::shared_ptr< ::cooperative_driving_hardware::LedValue > LedValuePtr;
typedef boost::shared_ptr< ::cooperative_driving_hardware::LedValue const> LedValueConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cooperative_driving_hardware::LedValue_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cooperative_driving_hardware::LedValue_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace cooperative_driving_hardware

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'cooperative_driving_hardware': ['/home/amjad/Desktop/pg2017w/ros/src/cooperative_driving/cooperative_driving_hardware/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::cooperative_driving_hardware::LedValue_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cooperative_driving_hardware::LedValue_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cooperative_driving_hardware::LedValue_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cooperative_driving_hardware::LedValue_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cooperative_driving_hardware::LedValue_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cooperative_driving_hardware::LedValue_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cooperative_driving_hardware::LedValue_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6a0c35f631f3f53c7b19b24b9d87c563";
  }

  static const char* value(const ::cooperative_driving_hardware::LedValue_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6a0c35f631f3f53cULL;
  static const uint64_t static_value2 = 0x7b19b24b9d87c563ULL;
};

template<class ContainerAllocator>
struct DataType< ::cooperative_driving_hardware::LedValue_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cooperative_driving_hardware/LedValue";
  }

  static const char* value(const ::cooperative_driving_hardware::LedValue_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cooperative_driving_hardware::LedValue_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Custom message type represent a reading from a distance sensor used for reading and writing\n\
\n\
# The frame_id (name) of this LED\n\
string frame_id\n\
# The current value of this LED\n\
# Values in [0, 1]\n\
float32 value\n\
";
  }

  static const char* value(const ::cooperative_driving_hardware::LedValue_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cooperative_driving_hardware::LedValue_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.frame_id);
      stream.next(m.value);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LedValue_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cooperative_driving_hardware::LedValue_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cooperative_driving_hardware::LedValue_<ContainerAllocator>& v)
  {
    s << indent << "frame_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.frame_id);
    s << indent << "value: ";
    Printer<float>::stream(s, indent + "  ", v.value);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COOPERATIVE_DRIVING_HARDWARE_MESSAGE_LEDVALUE_H
